language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3
sudo: required
before_install: 
    - bash prerequisites.sh
install: true
script: travis_wait mvn script    
    - python setup.py build
    - python setup.py install
    - bwa index Homo_sapiens_assembly19.fasta
    - samtools faidx Homo_sapiens_assembly19.fasta
    - cd test
    - ./test_snv.sh 10 20 ../Homo_sapiens_assembly19.fasta
