language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3
sudo: required
before_install: 
    - bash prerequisites.sh
install: true
script:
    - git clone https://github.com/samtools/htslib.git
    - sudo make -C htslib
    - git clone https://github.com/samtools/samtools.git
    - sudo make -C samtools
    - sudo cp samtools/samtools bin/
    - sudo cp samtools/misc/wgsim bin/
    - git clone https://github.com/samtools/bcftools.git
    - sudo make -C bcftools
    - sudo cp bcftools/bcftools bin/
    - git clone https://github.com/lh3/bwa.git
    - sudo make -C bwa
    - sudo cp bwa/bwa bin/
    - export PATH=/home/travis/build/MischaLundberg/bamsurgeon/bin:$PATH
    - python setup.py build
    - python setup.py install
    - bwa index test_data/Homo_sapiens_chr22_bamsurgeon_assembly19.fasta
#    - samtools faidx test_data/Homo_sapiens_chr22_bamsurgeon_assembly19.fasta
    - cd test
    - ./test_snv.sh 10 20 ../test_data/Homo_sapiens_chr22_bamsurgeon_assembly19.fasta
